# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

resources:
- repo: self

pool:
  name: free-pipeline

steps:
- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      myapp:$(Build.BuildId)

- task: Docker@2
  displayName: 'Push Docker image to Docker Hub'
  inputs:
    command: push
    repository: 'syrewkam/todo-backend'
    tags: |
      myapp-$(Build.BuildId)
    dockerRegistryServiceConnection: 'backend-docker-connection'